apiVersion: v1
kind: Secret
metadata:
  name: pg-root-crt
  namespace: edu-aleksandr-evstigneev
type: Opaque
stringData:
  root.crt: |
    -----BEGIN CERTIFICATE-----
    ...paste certificate...
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    ...paste certificate...
    -----END CERTIFICATE-----
